#pragma once

#define SYSCALLER_VERSION_MAJOR 1
#define SYSCALLER_VERSION_MINOR 3
#define SYSCALLER_VERSION_PATCH 2

#define SYSCALLER_VERSION_STRING "1.3.2"
#define SYSCALLER_VERSION_STRING_FULL "v" SYSCALLER_VERSION_STRING

#define SYSCALLER_APP_NAME "Bind"
#define SYSCALLER_WINDOW_TITLE SYSCALLER_APP_NAME " - " SYSCALLER_VERSION_STRING_FULL